# single test suite, non-parallel build.
language: node_js
services:
  - postgresql
node_js: "stable"
install: 
  - npm install
script:
  - npm test
env:
  NODE_ENV=test
cache:
  directories:
    - "node_modules"
branches:
  only:
    - develop
before_script:
  - psql -c 'create database sendittest;' -U postgres
after_success:
 - npm run coverage
