# single test suite, non-parallel build.
language: node_js

node_js: "stable"
install: 
  - npm install
script:
  - npm test
env:
  NODE_ENV=test
cache:
  directories:
    - "node_modules"
branches:
  only:
    - develop
after_success:
 - npm run coverage
